[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm ci && npm run build"
watchPatterns = ["backend/**"]

[deploy]
numReplicas = 1
startCommand = "cd backend && node dist/main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/v1"
healthcheckTimeout = 100

