[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["backend/**"]

[deploy]
numReplicas = 1
startCommand = "node dist/main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/v1"
healthcheckTimeout = 100

