$schema = "https://railway.app/railway.schema.json"

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node dist/main"
healthcheckPath = "/api/v1"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
